# Generated by Django 4.2.6 on 2023-10-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Роман', 'Роман'), ('Приключения', 'Приключения'), ('Триллер', 'Триллер'), ('Фантастика', 'Фантастика'), ('Детектив', 'Детектив')], default=('Роман', 'Роман'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
